name       : sbc
version    : '1.4'
release    : 2
component  : network.base
source     :
    - https://mirrors.edge.kernel.org/pub/linux/bluetooth/sbc-1.4.tar.xz : 518bf46e6bb3dc808a95e1eabad26fdebe8a099c1e781c27ed7fca6c2f4a54c9
license    : GPL-2.0-only
summary    : Bluetooth Subband Codec Library
description: |
    Bluetooth Subband Codec Library
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
