name       : sbc
version    : '1.5'
release    : 4
component  : network.base
source     :
    - https://mirrors.edge.kernel.org/pub/linux/bluetooth/sbc-1.5.tar.xz : 0cbad69823a99e8421fe0700e8cf9eeb8fa0c1ad28e8dbc2182b3353507931d2
license    : GPL-2.0-only
summary    : Bluetooth Subband Codec Library
description: |
    Bluetooth Subband Codec Library
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
