name       : sbc
version    : 1.3
release    : 1
source     :
    - https://www.kernel.org/pub/linux/bluetooth/sbc-1.3.tar.xz : e61022cf576f14190241e7071753fdacdce5d1dea89ffd704110fc50be689309
license    : LGPL-2.0 
summary    : Bluetooth Subband Codec Library
description: |
    Bluetooth Subband Codec Library
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
